Diary.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diary.Web.Controllers
{
    using Filters;
    using Logic.Operations;
    public class AccountController : Controller
    {
        [SkipAuthentication]
        public ActionResult LoginRegister(string message = null, bool badAlert = false)
        {
            ViewBag.message = message;
            ViewBag.badAlert = badAlert; //TODO replace ViewBag with Model
            return View();
        }
        [SkipAuthentication]
        public ActionResult logOut()
        {
            Authentication.AuthenticatedAs = null;
            return RedirectToAction("LoginRegister", new { message = "logged out successfully!" });
        }

        [HttpPost] [SkipAuthentication]
        public ActionResult checkCredentials(string username, string password)
        {
            try
            {
                if (UserOps.checkCredentials(username, password))
                {
                    Authentication.AuthenticatedAs = UserOps.returnUser(username);
                    return RedirectToAction("accountIndex");
                }
                else
                    return RedirectToAction("LoginRegister", "Account", new { message = "Invalid password!", badAlert = true });
            }
            catch
            {
                throw;
            }
        }

        public ActionResult accountIndex() => View();

        [HttpPost] [SkipAuthentication]
        public ActionResult registerUser(string firstname, string lastname, string email, string username, string password)
        {
            if (!UserOps.checkUsernameAvailability(username))
                return RedirectToAction("LoginRegister", new { message = $"the Username '{username}' exists!", badAlert = true });
            else if (string.IsNullOrWhiteSpace(firstname) || 
                        string.IsNullOrWhiteSpace(lastname) ||
                        string.IsNullOrWhiteSpace(email) ||
                        string.IsNullOrWhiteSpace(username) ||
                        string.IsNullOrWhiteSpace(password))
            {
                return RedirectToAction("LoginRegister", new { message = "Please fill in all fields", badAlert = true });
            }
            else
            {
                Authentication.AuthenticatedAs = UserOps.createUser(username, firstname, lastname, password, email);
                return RedirectToAction("accountIndex", "Account");
            }
        }
    }
}

Diary.Web/Controllers/AdminControlCentreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diary.Web.Controllers
{
    using Filters;
    using Ops = Logic.Operations;
    public class AdminControlCentreController : Controller
    {
        [RestrictedAccess]
        public ActionResult adminIndex()
        {
            return View();
        }

        [RestrictedAccess]
        public ActionResult updateUser(int userId, string newUsername, string newPassword, string newfirstname, string newlastname, string newisadmin)
        {
            try
            {
                Ops.UserOps.updateUser(userId, newUsername, newPassword, newisadmin == "on" ? true : false, newfirstname, newlastname);
                TempData["message"] = $"User with username '{newUsername}' has been updated!";
                TempData["badAlert"] = false;

                return RedirectToAction("adminIndex");
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult createUser(string username, string password, string email, string firstname, string lastname, bool adminrights = false)
        {
            try
            {
                Ops.UserOps.createUser(username, firstname, lastname, password, email, adminrights);
                TempData["message"] = "user has been created!";
                return RedirectToAction("adminIndex");
            }
            catch
            {
                throw;
            }
        }

        [RestrictedAccess]
        public ActionResult deleteUser(int userId)
        {
            try
            {
                Ops.UserOps.deleteUser(userId);
                TempData["message"] = "user has been deleted!";
                return RedirectToAction("adminIndex");
            }
            catch
            {
                throw;
            }
        }
    }
}

Diary.Web/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diary.Web.Controllers
{
    using Ops = Logic.Operations;
    public class EntryController : Controller
    {
        // GET: Entry
        public ActionResult createEntry(string message = null, bool badAlert = false)
        {
            ViewBag.message = message;
            ViewBag.badAlert = badAlert;
            return View();
        }

        [HttpPost]
        public ActionResult registerEntry(string title, string mood, string content)
        {
            try
            {
                Ops.EntryOps.createEntry(Authentication.AuthenticatedAs.Id, title, content, mood);
                return RedirectToAction("Index", "Home", new { message = "entry has been created!", badAlert = false });
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult updateValues(int id, string title, string content)
        {
            Ops.EntryOps.updateEntry(id, title, content);
            return RedirectToAction("Index", "Home", new { message = "entry updated!", badAlert = false });
        }
    }
}

Diary.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diary.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string message = null, bool badAlert = false)
        {
            ViewBag.message = message;
            ViewBag.badAlert = badAlert;
            return View();
        }
    }
}

Diary.Web/Views/AdminControlCentre/adminIndex.cshtml
@{
    ViewBag.Title = "admin control panel";
}

@using Ops = Diary.Logic.Operations;

<div class="jumbotron">
    <h2>Admin centre</h2>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#createUser">Create a new User</button>
</div>

Users:
<table class="table table-hover">
    <thead>
        <tr>
            <td>
                Id
            </td>
            <td>
                username
            </td>
            <td>
                email
            </td>
            <td>
                date created
            </td>
            <td>
                Entries
            </td>
            <td>
                Edit
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Ops.UserOps.getAllUsers())
        {
        <tr>
            <td>
                @user.Id
            </td>
            <td>
                @user.userName
            </td>
            <td>
                @user.email
            </td>
            <td>
                @user.dateCreated.ToString("dd/MMMM/yyyy")
            </td>
            <td>
                @user.diaryEntries.Count()
            </td>
            <td>
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#@string.Concat("userForm", user.Id)">Edit</button>
            </td>
            <td>
                @Html.ActionLink("Delete", "deleteUser", new { userId = user.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        }
    </tbody>
</table>

@foreach (var user in Ops.UserOps.getAllUsers())
{
    <div class="modal fade" id="@string.Concat("userForm", user.Id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">@user.userName</h4>
                </div>
                <div class="modal-body">
                    <form method="post" action="updateUser">
                        <input type="hidden" name="userId" value="@user.Id" />
                        Username: <input class="form-field form-control" type="text" name="newUsername" value="@user.userName" />
                        Password: <input class="form-field form-control" type="password" name="newPassword" value="placeholder" />
                        First Name: <input class="form-field form-control" type="text" name="newfirstname" value="@user.firstName" />
                        Last Name: <input class="form-field form-control" type="text" name="newlastname" value="@user.lastName" />
                         @if (user.isAdmin == true)
                        {
                        <p>Admin rights: </p><input type="checkbox" name="newisadmin" checked="checked" />
                        }
                        else if (user.isAdmin == false)
                        {
                        <p>Admin rights: </p><input type="checkbox" name="newisadmin" />
                        }
                        <input class="form-field form-control" type="submit" name="submitBtn" value="Save!" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}


<div class="modal fade" id="createUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Create a new user</h4>
                </div>
                <div class="modal-body">
                    <form method="post" action="createUser">
                        Username: <input type="text" class="form-control form-field" name="username" />
                        Password: <input type="password" class="form-control form-field" name="password" />
                        Email: <input type="email" class="form-control form-field" name="email" />
                        First Name: <input type="text" class="form-control form-field" name="firstname" />
                        First Name: <input type="text" class="form-control form-field" name="lastname" />
                        Admin Rights? <input type="checkbox" class="form-field" value="true" name="adminrights" />
                        <input class="form-field btn btn-info" type="submit" value="Save!" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

Diary.Web/Views/Entry/createEntry.cshtml
@{
    ViewBag.Title = "createEntry";
}

<h2>create an Entry</h2>
    <div class="row">
        <div class="col-xs-12" style="align-self: center">
            <form method="post" action="registerEntry">
                <div class="col-xs-3">
                    <input type="text" class="form-field form-control" name="title" placeholder="Title" />
                    <input type="hidden" name="mood" class="moodValHidden" />

                    <div class="dropdown">
                         <button class="moodDropdown form-field btn btn-info" data-toggle="dropdown" id="moodSelector">What mood are you in? <span class="caret"></span>
                         </button>
                        <ul class="dropdown-menu">
                            <li class="alert-success"><a href="#">Top o' the world!</a></li>
                            <li class="alert-success"><a href="#">Good</a></li>
                            <li class="alert-info"><a href="#">Meh</a></li>
                            <li class="alert-warning"><a href="#">Bad</a></li>
                            <li class="alert-warning"><a href="#">Rubbish</a></li>
                        </ul>
                    </div>

                    <input type="submit" class="btn btn-info form-field" value="Save!" />
                </div>
                <div class="col-xs-9">
                    <textarea name="content" maxlength="5000" class="form-field form-control" style="width: 7000px" cols="100" rows="30"></textarea>
                </div>
            </form>
        </div>
    </div>

<script>
    $(function(){
        $(".dropdown-menu li a").click(function(){
            $(".moodDropdown").text($(this).text());
            $(".moodValHidden").val($(this).text());
        });
    });
</script>

Diary.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    var entries = Ops.EntryOps.returnEntries(Authentication.AuthenticatedAs.Id);
}

@using Ops = Diary.Logic.Operations;
<div class="jumbotron">
    <h1>Diary</h1>
    <p class="lead">A place where you can store your thoughts, ramblings, and worries</p>
</div>

<div class="row">
    <div class="col-xs-12">
        Diary entries:
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>
                        Id
                    </td>
                    <td>
                        Title
                    </td>
                    <td>
                        Mood
                    </td>
                    <td>
                        Date created
                    </td>
                    <td>
                        Last modified
                    </td>
                    <td>
                        Edit
                    </td>
                </tr>
            </thead>
            @foreach (var entry in entries)
            {
                <tr>
                    <td>
                        @entry.id
                    </td>
                    <td>
                        @entry.title
                    </td>
                    <td>
                        @entry.mood
                    </td>
                    <td>
                        @entry.dateCreated.Date.ToString("dd/MMMM/yyyy")
                    </td>
                    <td>
                        @entry.LastEdited.Date.ToString("dd/MMMM/yyyy")
                    </td>
                    <td>
                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#@string.Concat("EntryForm", entry.id)">Edit</button>
                    </td>
                </tr>
            }
        </table>
        @if (Authentication.AuthenticatedAs.diaryEntries.Count() == 0)
        {
            <center><h3>No Entries? @Html.ActionLink("Create one!", "createEntry", "Entry")</h3></center>
        }


    </div>
</div>

@foreach (var entry in entries)
{
    <div class="modal fade" id="@string.Concat("EntryForm", entry.id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">@entry.title</h4>
                </div>
                <div class="modal-body">
                    <form method="post" action="Entry/updateValues">
                        Title: <input class="form-field form-control" type="text" name="title" value="@entry.title" />
                        <input type="hidden" name="id" value="@entry.id" />
                        Content: <textarea rows="30" class="form-field form-control" name="content">@entry.content</textarea>
                        <input type="submit" value="Save!" class="btn btn-info" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

Diary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Diary</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Diary", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Create", "createEntry", "Entry")</li>
                    @if (Authentication.isAuthenticated)
                    {
                        if (Authentication.AuthenticatedAs.isAdmin)
                        {
                            <li>@Html.ActionLink("Admin", "adminIndex", "AdminControlCentre")</li>
                        }
                    }
                </ul>
                @if (Authentication.isAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><i class="fa fa-user"></i> @Html.ActionLink("Account", "accountIndex", "Account")</li>
                        <li>@Html.ActionLink("Log Out", "logOut", "Account")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if ((string)TempData["message"] != null)
        {
            if ((bool)TempData["badAlert"])
            {
                <div class="alert alert-danger">
                    @TempData["message"].ToString()
                </div>
            }
            else
            {
                <div class="alert alert-info">
                    @TempData["message"].ToString()
                </div>
            }
              <script>$(function(){setTimeout(function(){$(".alert").slideUp(700)},5e3)});</script>      
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Diary. Designed and Developed by <a href="mailto:rhys.oconnor@outlook.com">Rhys O'Connor</a> 2016</p>
        </footer>
    </div>
</body>
</html>